import type { Socio, Membresia, Plan, Clase, Instructor, Asistencia, Pago } from "./types"

export const mockSocios: Socio[] = [
  {
    id: "1",
    nombre: "Carlos Martínez",
    email: "carlos@example.com",
    telefono: "+34 612 345 678",
    direccion: "Calle Mayor 123, Madrid",
    fechaNacimiento: "1990-05-15",
    foto: "/hombre-atletico.jpg",
    planId: "1",
    planNombre: "Plan Mensual",
    estado: "activo",
    fechaInicio: "2024-01-15",
    fechaVencimiento: "2025-02-15",
  },
  {
    id: "2",
    nombre: "Ana García",
    email: "ana@example.com",
    telefono: "+34 623 456 789",
    direccion: "Avenida Central 45, Barcelona",
    fechaNacimiento: "1988-08-22",
    foto: "/mujer-fitness.jpg",
    planId: "2",
    planNombre: "Plan Trimestral",
    estado: "activo",
    fechaInicio: "2024-11-01",
    fechaVencimiento: "2025-02-01",
  },
  {
    id: "3",
    nombre: "Luis Fernández",
    email: "luis@example.com",
    telefono: "+34 634 567 890",
    direccion: "Plaza España 78, Valencia",
    fechaNacimiento: "1995-03-10",
    planId: "1",
    planNombre: "Plan Mensual",
    estado: "vencido",
    fechaInicio: "2024-11-20",
    fechaVencimiento: "2024-12-20",
  },
]

export const mockMembresias: Membresia[] = [
  {
    id: "1",
    socioId: "1",
    socioNombre: "Carlos Martínez",
    planId: "1",
    planNombre: "Plan Mensual",
    fechaInicio: "2024-01-15",
    fechaVencimiento: "2025-02-15",
    monto: 45,
    estado: "activa",
    metodoPago: "tarjeta",
    notas: "Renovación automática",
  },
  {
    id: "2",
    socioId: "2",
    socioNombre: "Ana García",
    planId: "2",
    planNombre: "Plan Trimestral",
    fechaInicio: "2024-11-01",
    fechaVencimiento: "2025-02-01",
    monto: 120,
    estado: "activa",
    metodoPago: "transferencia",
  },
]

export const mockPlanes: Plan[] = [
  {
    id: "1",
    nombre: "Plan Mensual",
    descripcion: "Acceso completo al gimnasio durante 30 días",
    precio: 45,
    duracion: 1,
    duracionTipo: "meses",
    beneficios: ["Acceso ilimitado", "Todas las clases", "Vestuario"],
    activo: true,
  },
  {
    id: "2",
    nombre: "Plan Trimestral",
    descripcion: "Acceso completo durante 3 meses con descuento",
    precio: 120,
    duracion: 3,
    duracionTipo: "meses",
    beneficios: ["Acceso ilimitado", "Todas las clases", "Vestuario", "1 sesión personal trainer"],
    activo: true,
    popular: true,
  },
  {
    id: "3",
    nombre: "Plan Anual",
    descripcion: "El mejor precio por 12 meses",
    precio: 400,
    duracion: 12,
    duracionTipo: "meses",
    beneficios: [
      "Acceso ilimitado",
      "Todas las clases",
      "Vestuario",
      "4 sesiones personal trainer",
      "Nutricionista gratis",
    ],
    activo: true,
  },
]

export const mockClases: Clase[] = [
  {
    id: "1",
    nombre: "CrossFit",
    instructorId: "1",
    instructorNombre: "Carlos Ruiz",
    diaSemana: ["Lunes", "Miércoles", "Viernes"],
    horaInicio: "18:00",
    duracion: 60,
    cupoMaximo: 20,
    descripcion: "Entrenamiento funcional de alta intensidad",
    estado: "activa",
    inscritos: 18,
  },
  {
    id: "2",
    nombre: "Yoga",
    instructorId: "2",
    instructorNombre: "Ana Martínez",
    diaSemana: ["Martes", "Jueves"],
    horaInicio: "10:00",
    duracion: 60,
    cupoMaximo: 15,
    descripcion: "Yoga para todos los niveles",
    estado: "activa",
    inscritos: 12,
  },
]

export const mockInstructores: Instructor[] = [
  {
    id: "1",
    nombre: "Carlos Ruiz",
    email: "carlos.ruiz@gym.com",
    telefono: "+34 645 678 901",
    foto: "/entrenador-hombre.jpg",
    especialidades: ["CrossFit", "HIIT", "Funcional"],
    biografia: "10 años de experiencia en entrenamiento funcional",
    estado: "activo",
    clasesAsignadas: 8,
  },
  {
    id: "2",
    nombre: "Ana Martínez",
    email: "ana.martinez@gym.com",
    telefono: "+34 656 789 012",
    foto: "/instructora-yoga.jpg",
    especialidades: ["Yoga", "Pilates", "Meditación"],
    biografia: "Certificada en Hatha y Vinyasa Yoga",
    estado: "activo",
    clasesAsignadas: 6,
  },
]

export const mockAsistencias: Asistencia[] = [
  {
    id: "1",
    socioId: "1",
    socioNombre: "Carlos Martínez",
    claseId: "1",
    claseNombre: "CrossFit",
    fecha: "2024-12-20",
    horaEntrada: "17:55",
    horaSalida: "19:10",
    tipo: "clase",
  },
  {
    id: "2",
    socioId: "2",
    socioNombre: "Ana García",
    fecha: "2024-12-20",
    horaEntrada: "08:30",
    tipo: "libre",
  },
]

export const mockPagos: Pago[] = [
  {
    id: "1",
    socioId: "1",
    socioNombre: "Carlos Martínez",
    concepto: "Membresía Mensual - Enero 2025",
    monto: 45,
    metodoPago: "tarjeta",
    estado: "pagado",
    fecha: "2024-01-15",
  },
  {
    id: "2",
    socioId: "2",
    socioNombre: "Ana García",
    concepto: "Membresía Trimestral",
    monto: 120,
    metodoPago: "transferencia",
    estado: "pagado",
    fecha: "2024-11-01",
  },
]
